server:
  port: 9999

spring:
  application:
    name: config-server-git
  cloud:
    config:
      server:
        git:
          uri: "https://github.com/ghostnsnow/config-server-repo.git"
          search-paths:
            - service-a
          skipSslValidation: true
          default-label: main
          timeout: 5
          clone-on-start: true
          force-pull: true
  profiles:
    active: git

logging:
  level:
    org.springframework.cloud.config: DEBUG

management:
  endpoints:
    web:
      exposure:
        include:
          - "*"

encrypt:
  key: "gDI3MR5knMynPewa0dv1SsQosrWUZDvQM5ajIufpMagVaRxdsHnItrE3wpk/RwHC"